### ISSUE TITLE
Purpose of this repo

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/sublimetext.github.io#1]
I found this while digging through the org's repos and I do not think there is any purpose for this site any more now that http://sublime.wbond.net exists.

**Comment by vors** [comment]
Currently http://sublimetext.github.io/ contains a template page. I think it make sense to put something meaningful there.

**Comment by math2001** [comment]
http://sublimetext.github.io/: got a 404 here...

**Comment by FichteFoll** [comment]
It's whatever. I mainly use this repo for organizational issues now.
