### ISSUE TITLE
Update organization of the SublimeText org and cleaning up

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/sublimetext.github.io#2]
I'll be using this repository for organization-related issues. This post has many mentions.

Basically, I applied this team to the [new github organization settings beta](https://github.com/orgs/improved-permissions) and it has been accepted a while ago. I used this opportunity to clean up a bit on the rights and would like you to know about this.

Originally, this team was created to group Sublime Text-related repositories, mostly packages, for users to find since Package Control wasn't a thing back then. This has drastically changed over the past yearrs however, which is why I want to rearrange things a bit.
### The general idea

The general idea is to provide a platform for SublimeText-related repositories, that you would like others to have write access to. The most common use case is if you intend to abandon the repo and would like someone else (i.e. someone from the org) to take care of it. The other use case is just having input from other developers, I suppose.

If anyone wishes to add a collaborator to his repo that is not in this organization, they can now do so by simply _adding them as a collaborator_, as if it was your personal repo. The difference is that additionally @SublimeText/developers has write access to the repo, and @SublimeText/core admin access in case the repo is abandoned.

If you have any questions regarding this, please comment below.
## 
### Changes to the developers team

@SublimeText/developers: This team now gets **write access to each repository** (previously admin), while the original creator of it gets admin access by adding him as a collaborator to his project. This should also happen for newly created repos. While the old system worked (with everyone having admin access to almost all repos), this system is more secure for the actual repo owner and having it in this team just "allows" members to do changes or merge issues/pull requests. Previously, the admin right was needed in order to allow cretaion of repositories.
I hope I didn't miss anything here (I had to do everything manually), so if you want admin access to your repo back or anything similar, please mention ~~@SublimeText/core~~ @SublimeText/admins (had to rename the owner team), which contains users with the owner role. They can grant you access.
You can also mention me (@FichteFoll) or write me a mail (see my github profile).

If you do not want others to have write access to your repository, even though they had admin access for the past years already, you should move the repository to your private github account. If your package is listed on Package Control, **don't forget to update the url**!
## 
### Changes to individual teams or repos

@njlg: I removed your team, added you and your repositories to @SublimeText/developers and made all members of the team being able to write to it. You have admin privileges now, however (which you didn't have before). If you don't like this, please move your repositories to your personal account since the only purpose of this team is to allow other members to maintain or oversee your repositories.

@barneywilliams: I removed your "GoogleTesting" repo since it was practically empty and only contained a single commit that added a readme.

I wasn't sure who created PhpBeautifier (no email or name match from first commit), so I added @BarbUk as admin since he made all the following commits.

@guillermooo: I removed the PowerShell team and added @vors as a collaborator to the repos.

@mccombs: I removed your team as well, you are now a "collaborative admin" on your repo.

@netpro2k: Your SublimeBlockCursor fork on this org is behind your personal original repo. I suggest dissolving one of them.

@atomi: I removed the ColdFusionDevs team and added each member of them as a collaborator. The repo is currently _not_ in the @SublimeText/developers team. See below.
## 
### Remaining issues

The remaining repositories that do not grant any permissions to the @SublimeText/developers team are:
- ~~AAAPackageDev~~
- ~~ColdFusion~~
- ~~KnowledgeBase~~
- ~~PackageTesting~~
- ~~SublimeHg~~
- ~~sublimetext.github.com~~ (this will remain as owner-only, and should probably be renamed)

@guillermooo, @atomi: I recommend you to either move these repos to your private accounts or open the repo for the entire developers team (write access) to simplify how this org functions. It makes no sense to have a few select repos on this repos where only 4 people have write access (or a few hand-selected), just because they are owners of the org.

**Comment by jbrooksuk** [comment]
:+1:

**Comment by nnthnn** [comment]
Thanks for organizing all this!

**Comment by atomi** [comment]
Yeah thanks for this @FichteFoll. I've given the developers team write access to my ColdFusion plugin.  I don't recommend moving repos out as that creates a more likely chance that they won't get updated. 

Also, although I'm not working on my plugin now, I'd like to reserve the right to do so in the future. So I appreciate the restructuring. Thanks 😀

**Comment by vors** [comment]
I'm very excited about improved permissions. Manage a big org was not very easy. Thank you for heads up! 

I personally really liked my SublimeText org badge, I would miss it :)

**Comment by FichteFoll** [comment]
@vors, changed that ;)

Btw, the core team only exists for easy mentioning of all owners, in case you need them. It does not grant any rights.

**Comment by glenrobertson** [comment]
thanks @FichteFoll !

**Comment by adzenith** [comment]
Thanks for putting that time in! I appreciate it.

**Comment by mrchief** [comment]
:+1: :clap:

**Comment by FichteFoll** [comment]
ping @guillermooo

**Comment by FichteFoll** [comment]
another ping @guillermooo

Otherwise I'll just "open the gates". There likely won't happen anything anyway.

**Comment by FichteFoll** [comment]
I renamed the "Core" team to "Admins, which is more appropriate imo. I also added a few stray members to the "Developers" team.

I hope to sort things out with guillermooo later today, which will then hopefully complete everything mentioned in this issue.

**Comment by FichteFoll** [comment]
All remaining packages have been added to the developers team.
