### ISSUE TITLE
SublimeText Organization Cleanup 2020

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/sublimetext.github.io#3]
Hello @SublimeText/members,

I haven't contacted you since 2015 via #2, but it is time for another round of cleanup of the organization. Due to a recent event about 3 months ago with the co-owner of the SublimeTextIssues organization, where we as a community have tracked tickets for Sublime Text for the past 6 or so years, I am yet again going to reorganize permissions in order to provide more safety for everyone, for maintainers but also for users who installed a package that is a part of this organization.

As I mentioned in my past statement, the main purpose for this repository is to allow abandoned packages to continue being managed by active communtiy members so that the original maintainers don't have to concern themselves with recruiting collaborators or merging pull requests. Of course, it is also a place for collaborative development of packages that are still actively maintained and that won't change.

Previously, everyone who is part of the organization had write access to all repositories, which is an inherent security risk in the event that one user gets their password leaked and does not have 2-factor authentication, or they decide to abandon ship and take along as much as they can. Due to the aforementioned incident, this is a risk I am not willing to take anymore for the sake of other maintainers but also of users who have installed a package from this organization that could be hijacked with malicious code.

Thus, **I have removed everyone's write access to all repos.** However, **everyone remains an admin of the repositories they created** (or moved here). This measure will make it easier for me to add new members to the org and allow them to move their repositories without also granting full write access.

Instead, a select few active community members will be able to perform such actions in the absence of the original maintainers, so that they need not pay any mind whatsoever. It could be called a **marketplace for abandoned Sublime Text packages** that anyone could offer to take maintainership of and that is moderated by the @SublimeText/moderators. Every moderator must have "earned" my trust by showing activity in various parts of the community and showing some expertise in management. These aren't particularly hard requirements, but because of the previously mentioned incident I want to remain cautious. Secondly, since they have a lot of permissions of the org, they *must* have enabled 2-factor authentication.

**As such, please use this issue to apply for the moderator role!** If you are interested in what I described above, please speak up and I will be happy to add you to the moderator team, assuming you meet the preconditions. This is also a measure of testing acitvity since it requires explicit action on your behalf.

Should you run into any permission issues in the event I forgot to manually add you to a repository, please do speak up. As a human being, I am prone to making mistakes and I rely on those affected by them to make me aware of them, so I can attend to them quickly.

Thank you for your attention and have a nice weekend.

~FichteFoll

---

@sublimator, @barneywilliams, @guillermooo: I have removed your owner permissions on the organization and your membership on the admins team because neither of you has been active in the last 5 years, as far as I can tell. Again, this is a risk I am not willing to take anymore, so please don't take it personally, in case you are even reading this.

**Comment by TerminalFi** [comment]
I am not necessarily applying for a moderator role, in fact, at the moment I wouldn't have the time, I am rather dropping in my 2 cents. 

1. Thank you for your continued involvement in the ST community
2. I am 100% in support for this move forward. I believe this to be the more responsible approach to maintaining packages that would otherwise be dead while still providing some layer of security. Being a Security Engineer by trait, I highly appreciate this.

**Comment by adzenith** [comment]
Seems reasonable to me!

**Comment by jbrooksuk** [comment]
Yep, seems reasonable.

**Comment by FichteFoll** [comment]
Just wanted to let you know that as of now, the two moderators and admins of this org are myself and @keith-hall. That's a bus factor of >1 that I am at least comfortable to live with for the forseeable future. It should never stay on 1 for an extended period of time, however.

**Comment by FichteFoll** [comment]
I have also enabled discussions for this repository as a place for discussion regarding the organization as a whole. Feel free to use them.
